# needed to securely identify the workflow
name: autofix.ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  code:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-noble

    steps:
      - uses: actions/checkout@v4
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 📦 Install browsers
        run: pnpm playwright install

      - name: 🔠 Fix lint errors
        run: pnpm lint --fix

      - name: 🧪 Update unit test snapshots
        run: pnpm test:unit -u

      - name: 🏃 Update component test snapshots
        run: pnpm test:nuxt -u

      - name: 🖥️ Update browser test snapshots
        run: pnpm test:browser --update-snapshots

      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c
